def num_a():print(0, end="")
def num_b():print(1, end="")
def num_c():print(2, end="")
def num_d():print(3, end="")
def num_e():print(4, end="")
def num_f():print(5, end="")
def num_g():print(6, end="")
def num_h():print(7, end="")
def num_k():print(8, end="")
def num_z():print(9, end="")

num_k()
num_k() 
num_a()
num_a()
num_f()
num_f()
num_f()
num_d()
num_f()
num_d()
num_f()