URL_1 = "https://bonigarcia.dev/selenium-webdriver-java/data-types.html"
first_name = "Anton"
last_name = "Petrov"
address = "city Chita"
email = "kastiel750@mail.ru"
phone = "89999999991"
zip_code = ""
city = "Chita"
country = "Russia"
job_position = "surgeon"
company = "SkyPro"

URL_2 = "https://bonigarcia.dev/selenium-webdriver-java/slow-calculator.html"

URL_3 = "https://www.saucedemo.com/"